// frontend/components/HlsVideoPlayer.tsx
"use client"

import React, { useEffect, useRef } from 'react'
import Hls from 'hls.js'

interface HlsVideoPlayerProps {
  src: string
}

export default function HlsVideoPlayer({ src }: HlsVideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const hlsRef = useRef<Hls | null>(null)

  useEffect(() => {
    const video = videoRef.current
    if (!video) return

    // Clean up previous instance
    if (hlsRef.current) {
      hlsRef.current.destroy()
      hlsRef.current = null
    }

    if (Hls.isSupported()) {
      const hls = new Hls({
        maxMaxBufferLength: 30,
        enableWorker: true,
        lowLatencyMode: true
      })
      hls.loadSource(src)
      hls.attachMedia(video)
      hlsRef.current = hls
    } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
      // Safari/iOS native support
      video.src = src
    }

    return () => {
      if (hlsRef.current) {
        hlsRef.current.destroy()
        hlsRef.current = null
      }
    }
  }, [src])

  return (
    <div className="w-full rounded-3xl overflow-hidden bg-black shadow-[0_20px_50px_rgba(0,0,0,0.7)] aspect-video flex items-center justify-center border border-outline relative">
      <video 
        ref={videoRef} 
        controls 
        className="w-full h-full object-contain outline-none" 
        playsInline
        crossOrigin="anonymous"
      ></video>
    </div>
  )
}

// frontend/app/components/HlsVideoPlayer.vue
<template>
  <div class="video-player-container">
    <video ref="videoRef" controls class="video-element" playsinline></video>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import Hls from 'hls.js'

const props = defineProps({
  src: {
    type: String,
    required: true
  }
})

const videoRef = ref(null)
let hlsInstance = null

const initPlayer = () => {
  if (hlsInstance) {
    hlsInstance.destroy()
    hlsInstance = null
  }

  const video = videoRef.value
  if (!video) return

  if (Hls.isSupported()) {
    hlsInstance = new Hls({
      maxMaxBufferLength: 30
    })
    hlsInstance.loadSource(props.src)
    hlsInstance.attachMedia(video)
  } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
    // Soporte nativo para HLS (ej: Safari o iOS browsers)
    video.src = props.src
  }
}

onMounted(() => {
  initPlayer()
})

onBeforeUnmount(() => {
  if (hlsInstance) {
    hlsInstance.destroy()
  }
})

watch(() => props.src, () => {
  initPlayer()
})
</script>

<style scoped>
.video-player-container {
  width: 100%;
  border-radius: 12px;
  overflow: hidden;
  background-color: #000;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
  aspect-ratio: 16 / 9;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.video-element {
  width: 100%;
  height: 100%;
  object-fit: contain;
}
</style>
